### ISSUE TITLE
Accessibility - color blind check

### ISSUE THREAD

**Issue by allisonjw** [trishalanglois/refactor-tractor#11]
Add chrome extension of colorblinding. Run over site to see colors will affect all color visions disorders. 

Change colors of spans so there is more of a contrast.

**Comment by allisonjw** [comment]
The dev tool audit points out pretty much every span in the html that has a value of a number

- Background and foreground colors do not have a sufficient contrast ratio.

- Low-contrast text is difficult or impossible for many users to read. 

- https://dequeuniversity.com/rules/axe/3.1/color-contrast?application=lighthouse

**Comment by trishalanglois** [comment]
@allisonjw Can we take a look at this tomorrow together?  I want to change the colors of some of the font using Sass, so I thought this might be a good chance for me to dive into the syntax.  Here are the few spots I want to change the text color: 

- Weekly Friend Scoreboard -- the second place person
- All the small grey font on the bar graphs
