### ISSUE TITLE
Accessibility Audit

### ISSUE THREAD

**Issue by allisonjw** [trishalanglois/refactor-tractor#12]
There are a ton of audit tools available. The audit tool in dev tools shows a score of 35 / 100

- WAVE chrome extension

- Axe accessibility chrome extenstion

- https://www.w3.org/WAI/ER/tools/

**Comment by trishalanglois** [comment]
I downloaded the Chrome extension, but it didn't work on the first go.  I opted for the regular audit in dev tools, and we're currently at a 97!  Woo!  I think we should use that one as an audit tool, since that's available across all machines and we don't have to worry about calibrating.
