### ISSUE TITLE
Activity.js duplicate data

### ISSUE THREAD

**Issue by cammac60** [trishalanglois/refactor-tractor#3]
The class is storing all activity data as a property. I don't think we need to do this since we are essentially duplicating data that's already accessible. 

Fixing this would require changing quite a few of the methods because they access this.activityData. We would instead need to pass activity data as an argument when the functions are called and change the functions to reference the parameter rather than the property.

**Comment by trishalanglois** [comment]
Once we create our fetch requests, we can store those to a variable and refactor to take in that variable that's holding the data.
